name: Build Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install tizen workload
      run: |
        curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | bash
    - name: Build
      env:
        PULLREQUEST_ID: ${{ github.event.number }}
      run: |
        dotnet build Tizen.UIExtensions.sln
      working-directory: .
